---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "validator"
  namespace: "abuse-api-dev"
  labels:
    app: "validator"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: "validator"
    spec:
      imagePullSecrets:
        -
          name: "k8s-artifactory-creds"
      containers:
        -
          name: "validator-rest"
          imagePullPolicy: "Always"
          image: "artifactory.secureserver.net:10014/docker-dcu-local/dcu-validator-api:dev"
          env:
          - name: BUILD_DATE
            value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          - name: REDIS
            value: phishnet-redis.abuse-api-dev.svc.cluster.local
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-validator
                key: password
          - name: ABUSE_API_UPDATE_URL
            value: http://api.abuse-api-dev.svc.cluster.local:5000/v1/abuse/tickets
          - name: sysenv
            value: dev
          - name: scheduler
            value: localhost
        -
          name: "validator-scheduler"
          imagePullPolicy: "Always"
          image: "artifactory.secureserver.net:10014/docker-dcu-local/dcu-validator-scheduler:dev"
          env:
          - name: BUILD_DATE
            value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          - name: REDIS
            value: phishnet-redis.abuse-api-dev.svc.cluster.local
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-validator
                key: password
          - name: ABUSE_API_UPDATE_URL
            value: http://api.abuse-api-dev.svc.cluster.local:5000/v1/abuse/tickets
          - name: DB_USER
            value: devuser
          - name: DB_HOST
            value: 10.22.188.208
          - name: DB
            value: devphishstory
          - name: COLLECTION
            value: incidents
          - name: sysenv
            value: dev
