apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

namespace: abuse-api-dev

images:
- name: docker-dcu-local.artifactory.secureserver.net/dcu-validator-scheduler
  newTag: dev

configMapGenerator:
- literals:
  - sysenv=dev
  - REDIS=phishnet-redis.abuse-api-dev.svc.cluster.local
  - DB_USER=devuser
  - DB_HOST=10.36.190.222
  - DB=devphishstory
  - API_UPDATE_URL=http://api.abuse-api-dev.svc.cluster.local:5000/v1/abuse/tickets
  - SSO_URL=https://sso.dev-godaddy.com
  - DOMAIN_SERVICE=domainservice-rest.abuse-api-dev.svc.cluster.local:8080
  - RESULT_BACKEND_HOSTNAME=godaddy-service-redis.abuse-api-dev.svc.cluster.local
  - ELASTIC_APM_ENVIRONMENT=dev
  name: env-specific-values
