# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schedule_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='schedule_service.proto',
  package='scheduler',
  syntax='proto3',
  serialized_pb=_b('\n\x16schedule_service.proto\x12\tscheduler\"8\n\x07Request\x12\x0e\n\x06ticket\x18\x01 \x01(\t\x12\r\n\x05\x63lose\x18\x02 \x01(\x08\x12\x0e\n\x06period\x18\x03 \x01(\x05\"\n\n\x08Response\"G\n\x12ValidationResponse\x12!\n\x06result\x18\x01 \x01(\x0e\x32\x11.scheduler.Result\x12\x0e\n\x06reason\x18\x02 \x01(\t*,\n\x06Result\x12\t\n\x05VALID\x10\x00\x12\x0b\n\x07INVALID\x10\x01\x12\n\n\x06LOCKED\x10\x02\x32\xc9\x01\n\tScheduler\x12\x38\n\x0b\x41\x64\x64Schedule\x12\x12.scheduler.Request\x1a\x13.scheduler.Response\"\x00\x12;\n\x0eRemoveSchedule\x12\x12.scheduler.Request\x1a\x13.scheduler.Response\"\x00\x12\x45\n\x0eValidateTicket\x12\x12.scheduler.Request\x1a\x1d.scheduler.ValidationResponse\"\x00\x62\x06proto3')
)

_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='scheduler.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOCKED', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=180,
  serialized_end=224,
)
_sym_db.RegisterEnumDescriptor(_RESULT)

Result = enum_type_wrapper.EnumTypeWrapper(_RESULT)
VALID = 0
INVALID = 1
LOCKED = 2



_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='scheduler.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticket', full_name='scheduler.Request.ticket', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='close', full_name='scheduler.Request.close', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='period', full_name='scheduler.Request.period', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=93,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='scheduler.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=105,
)


_VALIDATIONRESPONSE = _descriptor.Descriptor(
  name='ValidationResponse',
  full_name='scheduler.ValidationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='scheduler.ValidationResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reason', full_name='scheduler.ValidationResponse.reason', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=178,
)

_VALIDATIONRESPONSE.fields_by_name['result'].enum_type = _RESULT
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['ValidationResponse'] = _VALIDATIONRESPONSE
DESCRIPTOR.enum_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'schedule_service_pb2'
  # @@protoc_insertion_point(class_scope:scheduler.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'schedule_service_pb2'
  # @@protoc_insertion_point(class_scope:scheduler.Response)
  ))
_sym_db.RegisterMessage(Response)

ValidationResponse = _reflection.GeneratedProtocolMessageType('ValidationResponse', (_message.Message,), dict(
  DESCRIPTOR = _VALIDATIONRESPONSE,
  __module__ = 'schedule_service_pb2'
  # @@protoc_insertion_point(class_scope:scheduler.ValidationResponse)
  ))
_sym_db.RegisterMessage(ValidationResponse)



_SCHEDULER = _descriptor.ServiceDescriptor(
  name='Scheduler',
  full_name='scheduler.Scheduler',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=227,
  serialized_end=428,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddSchedule',
    full_name='scheduler.Scheduler.AddSchedule',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveSchedule',
    full_name='scheduler.Scheduler.RemoveSchedule',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ValidateTicket',
    full_name='scheduler.Scheduler.ValidateTicket',
    index=2,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_VALIDATIONRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCHEDULER)

DESCRIPTOR.services_by_name['Scheduler'] = _SCHEDULER

# @@protoc_insertion_point(module_scope)
