---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "validator"
  namespace: "abuse-api-prod"
  labels:
    app: "validator"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "validator"
  template:
    metadata:
      labels:
        app: "validator"
    spec:
      imagePullSecrets:
        -
          name: "dcu-artifactory-creds"
      containers:
        -
          name: "validator-scheduler"
          imagePullPolicy: "Always"
          image: "docker-dcu-local.artifactory.secureserver.net/dcu-validator-scheduler:REPLACE_WITH_GIT_COMMIT"
          env:
          - name: BUILD_DATE
            value: "THIS_STRING_IS_REPLACED_DURING_BUILD"
          - name: REDIS
            value: phishnet-redis.abuse-api-prod.svc.cluster.local
          - name: MIN_PERIOD
            value: "300"
          - name: MAX_PERIOD
            value: "90000"
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-phishstory-v2
                key: password
          - name: DB_USER
            value: sau_p_phishv2
          - name: DB_HOST
            value: 10.22.9.209
          - name: DB
            value: phishstory
          - name: COLLECTION
            value: incidents
          - name: JOBS_COLLECTION
            value: jobs
          - name: API_UPDATE_URL
            value: http://api.abuse-api-prod.svc.cluster.local:5000/v1/abuse/tickets
          - name: SSO_URL
            value: https://sso.godaddy.com
          - name: SSO_USER
            valueFrom:
              secretKeyRef:
                name: abuse-api-user
                key: username
          - name: SSO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: abuse-api-user
                key: password
          - name: SMDB_USERNAME
            valueFrom:
              secretKeyRef:
                name: smdb-validator
                key: username
          - name: SMDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: smdb-validator
                key: password
          - name: DOMAIN_SERVICE
            value: domainservice-rest.abuse-api-prod.svc.cluster.local:8080
          - name: BROKER_PASS
            valueFrom:
              secretKeyRef:
                name: amqp-shared-creds
                key: password
          - name: RESULT_BACKEND_HOSTNAME
            value: godaddy-service-redis.abuse-api-prod.svc.cluster.local
          - name: sysenv
            value: prod
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: apm-access
                key: url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: apm-access
                key: secret
          - name: ELASTIC_APM_ENVIRONMENT
            value: prod
