apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

namespace: abuse-api-prod

images:
- name: docker-dcu-local.artifactory.secureserver.net/dcu-validator-scheduler
  newTag: prod

configMapGenerator:
- literals:
  - sysenv=prod
  - REDIS=phishnet-redis.abuse-api-prod.svc.cluster.local
  - DB_USER=sau_p_phishv2
  - DB_HOST=p3plsocritmdb00-00-f0.prod.phx3.gdg
  - DB=phishstory
  - API_UPDATE_URL=https://abuse.api.int.godaddy.com/v1/abuse/tickets
  - SSO_URL=https://sso.gdcorp.tools
  - DOMAIN_SERVICE=domainservice-rest.abuse-api-prod.svc.cluster.local:8080
  - ELASTIC_APM_ENVIRONMENT=prod
  name: env-specific-values
