apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

namespace: abuse-api-ote

images:
- name: docker-dcu-local.artifactory.secureserver.net/dcu-validator-scheduler
  newTag: ote

configMapGenerator:
- literals:
  - sysenv=ote
  - REDIS=phishnet-redis.abuse-api-ote.svc.cluster.local
  - DB_USER=sau_o_phish
  - DB_HOST=10.22.9.209
  - DB=otephishstory
  - API_UPDATE_URL=http://api.abuse-api-ote.svc.cluster.local:5000/v1/abuse/tickets
  - SSO_URL=https://sso.ote-gdcorp.tools
  - DOMAIN_SERVICE=domainservice-rest.abuse-api-ote.svc.cluster.local:8080
  - RESULT_BACKEND_HOSTNAME=godaddy-service-redis.abuse-api-ote.svc.cluster.local
  - ELASTIC_APM_ENVIRONMENT=ote
  name: env-specific-values
