---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "validator"
  labels:
    app: "validator"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "validator"
  template:
    metadata:
      labels:
        app: "validator"
    spec:
      imagePullSecrets:
        -
          name: "dcu-artifactory-creds"
      containers:
        -
          name: "validator-scheduler"
          image: "docker-dcu-local.artifactory.secureserver.net/dcu-validator-scheduler"
          env:
          - name: MIN_PERIOD
            value: "300"
          - name: MAX_PERIOD
            value: "90000"
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-phishstory-v2
                key: password
          - name: COLLECTION
            value: incidents
          - name: JOBS_COLLECTION
            value: jobs
          - name: SSO_USER
            valueFrom:
              secretKeyRef:
                name: abuse-api-user
                key: username
          - name: SSO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: abuse-api-user
                key: password
          - name: SMDB_USERNAME
            valueFrom:
              secretKeyRef:
                name: smdb-validator
                key: username
          - name: SMDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: smdb-validator
                key: password
          - name: MULTIPLE_BROKERS
            valueFrom:
              secretKeyRef:
                name: amqp-shared-creds
                key: multiple_brokers_grandma
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: apm-access
                key: url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: apm-access
                key: secret