version: 1

disable_existing_loggers: False

formatters:
    simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    detailed:
        format: '[%(levelname)s:%(asctime)s:%(filename)s:%(lineno)s - %(funcName)20s() ] %(message)s'
        datefmt:  '%Y-%m-%d %I:%M:%S%p'


handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: detailed
        stream: ext://sys.stdout


loggers:
    suds:
        level: ERROR
        handlers: [console]
        propogate: no

root:
    level: INFO
    handlers: [console]
